version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    restart: unless-stopped
    # For development, you can use volumes to mount your code
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
      # Add any other environment variables your app needs
      - VITE_APP_BASE_NAME=/
      - VITE_APP_API_URL=http://10.0.0.18:8001/
      - VITE_APP_SOCKET_URL=ws://10.0.0.18:8001
